### ISSUE TITLE
Assert triggering when load-balancing a PABLO tree with user data

### ISSUE THREAD

**Issue by arnodu** [optimad/bitpit#140]
Hi,

[This](https://github.com/optimad/bitpit/blob/e13fa5580c1858f837545818b5f093763adf03d3/src/PABLO/ParaTree.hpp#L920) assert triggers when I load balance my PABLO octree with user data.

Here is a short reproducer to compile in debug and run with at least 2 MPI :
[PABLO_test3.cpp.txt](https://github.com/optimad/bitpit/files/5927429/PABLO_test3.cpp.txt)

**Comment by andrea-iob** [comment]
I've tried your test case and I'm able to reproduce the problem. I'm looking into it.

**Comment by andrea-iob** [comment]
Pull request #141 should fix the problem. It should also fix the compact-families partitioning on three dimensional trees. Could you please check if the problem is now fixed (the changes are on the "PABLO.fix.family.partitioning" branch)? 

We have added your test case among the integrations test of PABLO, are you ok with that?

**Comment by arnodu** [comment]
Of course you can use the test case.

Looks like the issue is fixed on 490648c9ce957f830b6dcedde666b8f8ea3f83d4 , thanks.

**Comment by arnodu** [comment]
Now that this issue is out of the way, we still have issues when load balancing results in MPI processes with 0 octants. Probably a totally different issue, though.

For instance when i try to `adapt()` when a process has 0 octants, I get a segfault at [LocalTree.cpp#L1933](https://github.com/optimad/bitpit/blob/e13fa5580c1858f837545818b5f093763adf03d3/src/PABLO/LocalTree.cpp#L1933)

**Comment by andrea-iob** [comment]
We found a problem with empty partitions, it think this is the same issue you are experiencing. I've updated the branch "PABLO.fix.family.partitioning" (I did a force updated, if you have already pulled from that branch you need to reset your local branch to the online version). We don't use that much the partitioning routine that keeps families compact, thanks for helping us fixing it.
